name             'ha-mysql'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ha-mysql'
long_description 'Installs/Configures ha-mysql'
version          '0.1.0'

depends 'mysql', '~> 5.4.3'
depends 'hostsfile', '~> 2.4.5'
