# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "db1" do |db1|
    db1.vm.hostname = "db1"
    db1.omnibus.chef_version = :latest
    db1.vm.box = "chef/ubuntu-14.04"
    db1.vm.network :private_network, ip: "192.168.255.1"
    db1.berkshelf.enabled = true
    db1.vm.provision :chef_solo do |chef|
      chef.json = {
        mysql: {
          server_root_password: 'rootpass',
          server_debian_password: 'debpass',
          server_repl_password: 'replpass',
          allow_remote_root: true
        }
      }
      
      chef.run_list = [
        "recipe[ha-mysql::default]",
        "recipe[mysql::server]"
      ]
    end
  end

  config.vm.define "db2" do |db2|
    db2.vm.hostname = "db2"
    db2.omnibus.chef_version = :latest
    db2.vm.box = "chef/ubuntu-14.04"
    db2.vm.network :private_network, ip: "192.168.255.2"
    db2.berkshelf.enabled = true
    db2.vm.provision :chef_solo do |chef|
      chef.json = {
        mysql: {
          server_root_password: 'rootpass',
          server_debian_password: 'debpass',
          server_repl_password: 'replpass',
          allow_remote_root: true
        }
      }
      
      chef.run_list = [
        "recipe[ha-mysql::default]",
        "recipe[mysql::server]"
      ]
    end
  end

  config.vm.define "client1" do |client1|
    client1.vm.hostname = "client1"
    client1.omnibus.chef_version = :latest
    client1.vm.box = "chef/ubuntu-14.04"
    client1.vm.network :private_network, ip: "192.168.255.3"
    client1.berkshelf.enabled = true
    client1.vm.provision :chef_solo do |chef|
      chef.run_list = [
        "recipe[mysql::client]"
      ]
    end
  end
end

